import { promises as fs } from 'node:fs';
import path from 'node:path';

const DEFAULT_ENV_FILE = '.ju-office.env';
const ENV_KEY_PATTERN = /^[A-Z_][A-Z0-9_]*$/;

function sanitizeEnvValue(rawValue: string): string {
  const trimmed = rawValue.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

export function parseEnvContent(content: string): Record<string, string> {
  const map: Record<string, string> = {};
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const index = trimmed.indexOf('=');
    if (index <= 0) {
      continue;
    }

    const key = trimmed.slice(0, index).trim();
    if (!ENV_KEY_PATTERN.test(key)) {
      continue;
    }

    const value = sanitizeEnvValue(trimmed.slice(index + 1));
    if (!value) {
      continue;
    }
    map[key] = value;
  }

  return map;
}

export async function readLocalEnv(rootDir: string, envFile = DEFAULT_ENV_FILE): Promise<Record<string, string>> {
  const envPath = path.join(rootDir, envFile);
  try {
    const content = await fs.readFile(envPath, 'utf8');
    return parseEnvContent(content);
  } catch (error) {
    const code =
      error && typeof error === 'object' && 'code' in error && typeof (error as { code?: unknown }).code === 'string'
        ? ((error as { code: string }).code as string)
        : '';
    if (code === 'ENOENT') {
      return {};
    }
    throw error;
  }
}

export async function loadLocalEnvFile(rootDir: string, envFile = DEFAULT_ENV_FILE): Promise<void> {
  const values = await readLocalEnv(rootDir, envFile);
  for (const [key, value] of Object.entries(values)) {
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

export async function writeLocalEnv(rootDir: string, values: Record<string, string>, envFile = DEFAULT_ENV_FILE): Promise<string> {
  const envPath = path.join(rootDir, envFile);
  const lines: string[] = [
    '# Ju Office local auth tokens',
    '# Generated by: npm run ju -- setup',
    ''
  ];

  for (const key of Object.keys(values).sort()) {
    lines.push(`${key}=${values[key]}`);
  }
  lines.push('');

  await fs.writeFile(envPath, lines.join('\n'), 'utf8');
  await fs.chmod(envPath, 0o600).catch(() => undefined);
  return envPath;
}

